// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kscep/internal/biz"
	"kscep/internal/conf"
	"kscep/internal/server"
	"kscep/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	helloWorldUsecase := biz.NewHelloWorldUsecase(logger)
	helloWorldService := service.NewHelloWorldService(helloWorldUsecase, logger)
	httpServer := server.NewGinhttpServer(confServer, logger, helloWorldService)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
